# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 495534b3b24b835e992b660f3dbcc8ca9b5997e345d022a483fc68c7aeb0a3485ccf991dc9e125e01705c50c855cef569b0499e5c11f59ff3539c3893b2ce71a

test:
  secret_key_base: 5c57862948013445133e8741952ba6304a67fe316a9e5f18e597476972f3090d3a95ae09f2bf4f824cd02f3a0e1fabf4429eb201b27a40c92cb676016e503126

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
